version: '3.2'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    hostname: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_DATABASE=opencart
      - MYSQL_ROOT_PASSWORD=secure_password_here
    restart: always
    volumes:
      - mysql_data:/var/lib/mysql
  opencart:
    image: aamservices/opencart:latest
    restart: always
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - opencart_data:/var/www/html
    depends_on:
      - mysql
volumes:
  mysql_data:
    driver: local
  opencart_data:
    driver: local
